
```{r eval=FALSE}


# in bash terminal:
# conda activate spatial
library(CellChat)
library(Seurat)
library(tidyverse)
library(cowplot)
library(Matrix)
library(viridis)
library(presto)
library(harmony)
library(ggpubr)
library(DoubletFinder)
library(RColorBrewer)
library(ggrepel)
library(patchwork)
colfunc <- colorRampPalette(rev(brewer.pal(11, 'Spectral' )))
prediction.colfunc <- colorRampPalette(rev(brewer.pal(9, 'Purples' )[2:9]))

theme_set(theme_cowplot())

# setwd("/dfs3b/swaruplab/smorabit/analysis/FIRE_mouse_2021/hardcore_filtering/")
setwd("/dfs3b/swaruplab/smorabit/analysis/FIRE_mouse_2021/cellchat/")

# directories
data_dir <- "data/"
fig_dir <- 'figures/'


umap_theme <- theme(
  axis.line=element_blank(),
  axis.text.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks=element_blank(),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  panel.background=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  plot.background=element_blank()
)

# re-load:
seurat_obj <- readRDS('/dfs3b/swaruplab/smorabit/analysis/FIRE_mouse_2021/data/FIRE_mouse_seurat.rds')

```

Create CellChat object:
```{r eval=FALSE}

data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
labels <- Idents(seurat_obj)
meta <- data.frame(group = labels, row.names = names(labels))

cellchat <- createCellChat(object = data.input, meta = seurat_obj@meta.data, group.by = "clusternum_anno")

# set the LR-database:
CellChatDB <- CellChatDB.mouse
cellchat@DB <- CellChatDB


```

Data processing:

```{r eval=FALSE}

# subset by signaling genes:
cellchat <- subsetData(cellchat)

future::plan("multiprocess", workers = 8)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.mouse)

# infer the cell communication network:
cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
cellchat <- filterCommunication(cellchat, min.cells = 10)

# get the cell-cell communication network as a dataframe:
df.net <- subsetCommunication(cellchat)

# infer cell-cell communication at a signaling pathway level:
cellchat <- computeCommunProbPathway(cellchat)

# aggregated cell-cell communication network:
cellchat <- aggregateNet(cellchat)

# visualize aggregated net:
groupSize <- as.numeric(table(cellchat@idents))


pdf(paste0(fig_dir, 'aggregated_net.pdf'), width=10, height=10)
mat <- cellchat@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}
dev.off()


df.net[grep('PDG', df.net$pathway_name ),]

```

Data vis:

```{r eval=FALSE}

################################################################################
# Hierarchy plot
################################################################################

pathways.show <- c("PDGF")
vertex.receiver = c(10,14,15,18,19,21,29,30)

pdf(paste0(fig_dir, 'PDGF_hierarchy.pdf'), width=10, height=7)
netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver)
dev.off()

################################################################################
# circle plot
################################################################################

pdf(paste0(fig_dir, 'PDGF_circle.pdf'), width=10, height=10)
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
dev.off()

################################################################################
# chord plot
################################################################################

pdf(paste0(fig_dir, 'PDGF_chord.pdf'), width=10, height=10)
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
dev.off()

################################################################################
# heatmap
################################################################################

pdf(paste0(fig_dir, 'PDGF_heatmap.pdf'), width=10, height=10)
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
dev.off()

################################################################################
# Bubble
################################################################################
pdf(paste0(fig_dir, 'PDGF_bubble.pdf'), width=10, height=5)
netVisual_bubble(cellchat, signaling=pathways.show, remove.isolate = FALSE)
dev.off()

################################################################################
# Violin
################################################################################
pdf(paste0(fig_dir, 'PDGF_violin.pdf'), width=10, height=5)
plotGeneExpression(cellchat, signaling = pathways.show)
dev.off()

```

Systems analysis of cell-cell comm network:

```{r eval=FALSE}

# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups

pdf(paste0(fig_dir, 'signalingRole_net.pdf'), width=16, height=4)
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 16, height = 4, font.size = 10)
dev.off()


# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
gg1 <- netAnalysis_signalingRole_scatter(cellchat)
#> Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
# Signaling role analysis on the cell-cell communication networks of interest
gg2 <- netAnalysis_signalingRole_scatter(cellchat, signaling = pathways.show)
#> Signaling role analysis on the cell-cell communication network from user's input

pdf(paste0(fig_dir, 'PDGF_scatter.pdf'), width=10, height=5)
gg1 + gg2
dev.off()

```

Manifold learning:

```{r eval=FALSE}

cellchat <- computeNetSimilarity(cellchat, type = "functional")
cellchat <- netEmbedding(cellchat, type = "functional")
#> Manifold learning of the signaling networks for a single dataset
cellchat <- netClustering(cellchat, type = "functional")
#> Classification learning of the signaling networks for a single dataset
# Visualization in 2D-space
netVisual_embedding(cellchat, type = "functional", label.size = 3.5)

```


Run CellChat for 5xFAD and 5xFIRE separately:

```{r eval=FALSE}


data.input <- GetAssayData(seurat_obj, assay = "RNA", slot = "data")
labels <- Idents(seurat_obj)
meta <- data.frame(group = labels, row.names = names(labels))

cc_5xFAD <- createCellChat(
  object = data.input[,seurat_obj$DX == '5xFAD'],
  meta = seurat_obj@meta.data %>% subset(DX == '5xFAD'),
  group.by = "class"
)

cc_5xFIRE <- createCellChat(
  object = data.input[,seurat_obj$DX == '5xFIRE'],
  meta = seurat_obj@meta.data %>% subset(DX == '5xFIRE'),
  group.by = "class"
)


cc_PBS <- createCellChat(
  object = data.input[,seurat_obj$DX == '5xFIRE + PBS'],
  meta = seurat_obj@meta.data %>% subset(DX == '5xFIRE + PBS'),
  group.by = "class"
)

cc_trans <- createCellChat(
  object = data.input[,seurat_obj$DX == '5xFIRE + transplant'],
  meta = seurat_obj@meta.data %>% subset(DX == '5xFIRE + transplant'),
  group.by = "class"
)

# set the LR-database:
CellChatDB <- CellChatDB.mouse
cc_5xFAD@DB <- CellChatDB
cc_5xFIRE@DB <- CellChatDB
cc_PBS@DB <- CellChatDB
cc_trans@DB <- CellChatDB

################################################################################
# process data
################################################################################

future::plan("multiprocess", workers = 8)

# 5xFAD data
cc_5xFAD <- subsetData(cc_5xFAD)
cc_5xFAD <- identifyOverExpressedGenes(cc_5xFAD)
cc_5xFAD <- identifyOverExpressedInteractions(cc_5xFAD)
cc_5xFAD <- projectData(cc_5xFAD, PPI.mouse)
cc_5xFAD <- computeCommunProb(cc_5xFAD, raw.use = TRUE)
cc_5xFAD <- filterCommunication(cc_5xFAD, min.cells = 10)
df.net <- subsetCommunication(cc_5xFAD)
cc_5xFAD <- computeCommunProbPathway(cc_5xFAD)
cc_5xFAD <- aggregateNet(cc_5xFAD)
saveRDS(cc_5xFAD, file='data/cellchat_5xFAD.rds')

# 5xFIRE data
cc_5xFIRE <- subsetData(cc_5xFIRE)
cc_5xFIRE <- identifyOverExpressedGenes(cc_5xFIRE)
cc_5xFIRE <- identifyOverExpressedInteractions(cc_5xFIRE)
cc_5xFIRE <- projectData(cc_5xFIRE, PPI.mouse)
cc_5xFIRE <- computeCommunProb(cc_5xFIRE, raw.use = TRUE)
cc_5xFIRE <- filterCommunication(cc_5xFIRE, min.cells = 10)
df.net <- subsetCommunication(cc_5xFIRE)
cc_5xFIRE <- computeCommunProbPathway(cc_5xFIRE)
cc_5xFIRE <- aggregateNet(cc_5xFIRE)
saveRDS(cc_5xFIRE, file='data/cellchat_5xFIRE.rds')

# PBS data
cc_PBS <- subsetData(cc_PBS)
cc_PBS <- identifyOverExpressedGenes(cc_PBS)
cc_PBS <- identifyOverExpressedInteractions(cc_PBS)
cc_PBS <- projectData(cc_PBS, PPI.mouse)
cc_PBS <- computeCommunProb(cc_PBS, raw.use = TRUE)
cc_PBS <- filterCommunication(cc_PBS, min.cells = 10)
df.net <- subsetCommunication(cc_PBS)
cc_PBS <- computeCommunProbPathway(cc_PBS)
cc_PBS <- aggregateNet(cc_PBS)
saveRDS(cc_PBS, file='data/cellchat_PBS.rds')

# transplant data
cc_trans <- subsetData(cc_trans)
cc_trans <- identifyOverExpressedGenes(cc_trans)
cc_trans <- identifyOverExpressedInteractions(cc_trans)
cc_trans <- projectData(cc_trans, PPI.mouse)
cc_trans <- computeCommunProb(cc_trans, raw.use = TRUE)
cc_trans <- filterCommunication(cc_trans, min.cells = 10)
df.net <- subsetCommunication(cc_trans)
cc_trans <- computeCommunProbPathway(cc_trans)
cc_trans <- aggregateNet(cc_trans)
saveRDS(cc_trans, file='data/cellchat_trans.rds')


################################################################################
# merge datasets together:
################################################################################

object.list <- list(
  '5xFAD' = cc_5xFAD,
  '5xFIRE' = cc_5xFIRE,
  '5xFIRE + PBS'= cc_PBS,
  '5xFIRE + transplant'= cc_trans
)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))

################################################################################
# compare number of interactions
################################################################################

gg1 <- compareInteractions(cellchat, show.legend = F, group = c(1,2))
gg2 <- compareInteractions(cellchat, show.legend = F, group = c(1,2), measure = "weight")

pdf(paste0(fig_dir, 'compare_interactions.pdf'), width=6, height=3)
gg1 + gg2
dev.off()


gg1 <- netVisual_heatmap(cellchat)
#> Do heatmap based on a merged object
gg2 <- netVisual_heatmap(cellchat, measure = "weight")
#> Do heatmap based on a merged object
pdf(paste0(fig_dir, 'compare_interactions_heatmap.pdf'), width=12, height=6)
gg1 + gg2
dev.off()


pdf(paste0(fig_dir, 'compare_interactions_network.pdf'), width=12, height=6)
weight.max <- getMaxWeight(object.list, attribute = c("idents","count"))
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(object.list)) {
  netVisual_circle(object.list[[i]]@net$count, weight.scale = T, label.edge= F, edge.weight.max = weight.max[2], edge.width.max = 12, title.name = paste0("Number of interactions - ", names(object.list)[i]))
}

dev.off()




################################################################################
# compare pdgfb
################################################################################

vertex.receiver = c(1,2,3, 10,12)
table(seurat_obj$class)
pathways.show <- c("TGFb"); name <- 'TGFb'


pdf(paste0(fig_dir,'signaling/', name, '_circle_compare.pdf'), width=10, height=10)
par(mfrow = c(2,2), xpd=TRUE)
for (i in 1:length(object.list)) {
#for (i in c(1,4)) {

  netVisual_aggregate(object.list[[i]], signaling = pathways.show, layout = "circle", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(object.list)[i]))
}
dev.off()

pdf(paste0(fig_dir, 'signaling/', name, '_hierarchy_compare.pdf'), width=10, height=7)
for (i in 1:length(object.list)) {
  netVisual_aggregate(object.list[[i]], signaling = pathways.show, vertex.receiver = vertex.receiver, signaling.name = paste(pathways.show, names(object.list)[i]))
}
dev.off()


```

Identify conserved and context-specific pathways:

```{r eval=FALSE}

object.list <- list(
  '5xFAD' = cc_5xFAD,
  '5xFIRE' = cc_5xFIRE
)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))


cellchat <- computeNetSimilarityPairwise(cellchat, type = "functional")
cellchat <- netEmbedding(cellchat, type = "functional")
cellchat <- netClustering(cellchat, type = "functional")


pdf(paste0(fig_dir, 'embed_networks_compare_functional.pdf'), width=10, height=10)
netVisual_embeddingPairwise(cellchat, type = "functional", label.size = 3.5)
dev.off()




cellchat <- computeNetSimilarityPairwise(cellchat, type = "structural")
cellchat <- netEmbedding(cellchat, type = "structural")
cellchat <- netClustering(cellchat, type = "structural")


pdf(paste0(fig_dir, 'embed_networks_compare_structural.pdf'), width=10, height=10)
netVisual_embeddingPairwise(cellchat, type = "structural", label.size = 3.5)
#> 2D visualization of signaling networks from datasets 1 2
dev.off()


pdf(paste0(fig_dir, 'rank_similarity_functional.pdf'), width=5, height=10)
rankSimilarity(cellchat, type = "functional")
dev.off()


cellchat <- readRDS(file='data/cellchat_compare.rds')
saveRDS(cellchat, file='data/cellchat_compare.rds')


```
